server {
    listen 80;
    server_name 64.90.30.139;
    root /var/www/dsh-updater;
    autoindex on;
    charset utf-8;
    location / {
        try_files $uri =404;
        add_header Access-Control-Allow-Origin *;
    }
}
