; Chinese (Simplified) Language File for DSH Plugin Updater Installer
; Encoding: UTF-8

LangString addOrReinstall ${LANG_SIMPLIFIED_CHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPLIFIED_CHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPLIFIED_CHINESE} "${PRODUCTNAME} ${VERSION} 已经安装。请选择您要执行的操作，然后点击下一步继续。"
LangString appRunning ${LANG_SIMPLIFIED_CHINESE} "{{product_name}} 正在运行！请先关闭它，然后重试。"
LangString appRunningOkKill ${LANG_SIMPLIFIED_CHINESE} "{{product_name}} 正在运行！\n点击确定以结束进程"
LangString chooseMaintenanceOption ${LANG_SIMPLIFIED_CHINESE} "选择要执行的操作。"
LangString choowHowToInstall ${LANG_SIMPLIFIED_CHINESE} "选择安装 ${PRODUCTNAME} 的方式。"
LangString createDesktop ${LANG_SIMPLIFIED_CHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPLIFIED_CHINESE} "不卸载"
LangString dontUninstallDowngrade ${LANG_SIMPLIFIED_CHINESE} "不卸载（此安装包不支持降级安装）"
LangString failedToKillApp ${LANG_SIMPLIFIED_CHINESE} "无法终止 {{product_name}}。请先关闭它，然后重试。"
LangString installingWebview2 ${LANG_SIMPLIFIED_CHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPLIFIED_CHINESE} "已安装更新的 ${PRODUCTNAME} 版本！不建议安装旧版本。如果确实要安装此旧版本，建议先卸载当前版本。请选择您要执行的操作，然后点击下一步继续。"
LangString older ${LANG_SIMPLIFIED_CHINESE} "旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPLIFIED_CHINESE} "您的系统上已安装 ${PRODUCTNAME} 的 $R4 版本。建议先卸载当前版本再安装。请选择您要执行的操作，然后点击下一步继续。"
LangString silentDowngrades ${LANG_SIMPLIFIED_CHINESE} "此安装包不支持降级安装，无法继续静默安装，请使用图形界面安装程序。$\n"
LangString unableToUninstall ${LANG_SIMPLIFIED_CHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPLIFIED_CHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPLIFIED_CHINESE} "安装前卸载"
LangString unknown ${LANG_SIMPLIFIED_CHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPLIFIED_CHINESE} "WebView2 安装失败！没有它应用程序无法运行。请尝试重新启动安装程序。"
LangString webview2DownloadError ${LANG_SIMPLIFIED_CHINESE} "错误：下载 WebView2 失败 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPLIFIED_CHINESE} "WebView2 启动程序下载成功"
LangString webview2Downloading ${LANG_SIMPLIFIED_CHINESE} "正在下载 WebView2 启动程序..."
LangString webview2InstallError ${LANG_SIMPLIFIED_CHINESE} "错误：安装 WebView2 失败，退出代码 $1"
LangString webview2InstallSuccess ${LANG_SIMPLIFIED_CHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPLIFIED_CHINESE} "删除应用程序数据"
